import { z } from 'zod'
import { zodFunction } from 'openai/helpers/zod'

const Parameters = z.object({
  markdownContent: z.string().describe('The full CV content in Markdown syntax, generated by the AI based on user inputs. This would include sections like skills, experience, education, and more'),
})

export const createCV = zodFunction({ name: 'createCV', description: 'Creates a tailored PDF CV for John Pino based on user-specified details', parameters: Parameters })
