import { z } from 'zod'
import { zodFunction } from 'openai/helpers/zod'

const Parameters = z.object({
  searchQuery: z.string().describe('The search query generated by the assistant.'),
})

export const getContext = zodFunction({ name: 'getContext', description: 'Get the current context so you can answer. Call this when the user asks for something you don\'t have context for. You need to refine the search query to retrieve relevant documents from Pinecone.', parameters: Parameters })
